version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "mydb-2"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"